# Generated by Django 3.2.7 on 2021-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_fun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='student',
            name='activity_four',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='activity_one',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='activity_three',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='activity_two',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
