# Generated by Django 3.2.7 on 2021-09-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_fun', '0002_auto_20210907_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activity_four',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('swim', 'Swim'), ('hike', 'Hike'), ('bike', 'Bike'), ('kayak', 'Kayak'), ('art', 'Art')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity_one',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('swim', 'Swim'), ('hike', 'Hike'), ('bike', 'Bike'), ('kayak', 'Kayak'), ('art', 'Art')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity_three',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('swim', 'Swim'), ('hike', 'Hike'), ('bike', 'Bike'), ('kayak', 'Kayak'), ('art', 'Art')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity_two',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('swim', 'Swim'), ('hike', 'Hike'), ('bike', 'Bike'), ('kayak', 'Kayak'), ('art', 'Art')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=60),
        ),
    ]
