# Generated by Django 3.2.7 on 2021-09-23 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summer_fun', '0004_auto_20210911_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(choices=[('none', 'None'), ('swim', 'Swim'), ('hike', 'Hike'), ('bike', 'Bike'), ('kayak', 'Kayak'), ('art', 'Art')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='activity_four',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activity_one',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activity_three',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activity_two',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summer_fun.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summer_fun.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='activities',
            field=models.ManyToManyField(through='summer_fun.Schedule', to='summer_fun.Activity'),
        ),
    ]
