# Generated by Django 3.2.7 on 2021-12-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_fun', '0007_activity_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='session',
            field=models.CharField(max_length=1),
        ),
    ]
