# Generated by Django 3.2.7 on 2022-01-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summer_fun', '0009_auto_20220101_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='summer_fun.activity'),
        ),
    ]
